In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import os

In [2]:
jeju_mct = pd.read_csv('./data/JEJU_MCT_DATA.csv', encoding = 'cp949')
jeju_mct

,YM,MCT_NM,OP_YMD,MCT_TYPE,ADDR,UE_CNT_GRP,UE_AMT_GRP,UE_AMT_PER_TRSN_GRP,MON_UE_CNT_RAT,TUE_UE_CNT_RAT,...,HR_18_22_UE_CNT_RAT,HR_23_4_UE_CNT_RAT,LOCAL_UE_CNT_RAT,RC_M12_MAL_CUS_CNT_RAT,RC_M12_FME_CUS_CNT_RAT,RC_M12_AGE_UND_20_CUS_CNT_RAT,RC_M12_AGE_30_CUS_CNT_RAT,RC_M12_AGE_40_CUS_CNT_RAT,RC_M12_AGE_50_CUS_CNT_RAT,RC_M12_AGE_OVR_60_CUS_CNT_RAT
0,202301,통큰돼지,20110701,가정식,제주 제주시 용담이동 2682-9번지 통큰돼지,2_10~25%,3_25~50%,4_50~75%,0.161290,0.032258,...,0.838710,0.000000,0.707763,0.610,0.390,0.103,0.124,0.245,0.387,0.142
1,202301,해변,20050407,단품요리 전문,제주 제주시 애월읍 애월리 410-6번지,4_50~75%,5_75~90%,5_75~90%,0.090909,0.121212,...,0.560606,0.000000,0.230928,0.542,0.458,0.221,0.201,0.195,0.244,0.139
2,202301,한그릇,20120919,단품요리 전문,제주 서귀포시 색달동 2315-1번지 한그릇,4_50~75%,4_50~75%,3_25~50%,0.224719,0.112360,...,0.000000,0.000000,0.347059,0.529,0.471,0.138,0.309,0.342,0.164,0.047
3,202301,협재해녀의집,20130627,가정식,제주 제주시 한림읍 협재리 1459-2번지,4_50~75%,4_50~75%,3_25~50%,0.000000,0.271739,...,0.152174,0.000000,0.016096,0.484,0.516,0.323,0.321,0.209,0.109,0.039
4,202301,까망꼬숑,20220826,단품요리 전문,제주 제주시 노형동 3784-12번지 1층,2_10~25%,4_50~75%,5_75~90%,0.272727,0.121212,...,0.727273,0.090909,0.264463,0.513,0.487,0.412,0.311,0.176,0.076,0.025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67921,202312,미나리,20230630,가정식,제주 제주시 연동 291-24번지 연동,4_50~75%,5_75~90%,3_25~50%,0.192000,0.216000,...,0.216000,0.000000,0.724662,0.546,0.454,0.091,0.261,0.313,0.241,0.094
67922,202312,종달리엔심야식당,20210513,가정식,제주 제주시 구좌읍 종달리 1935-1번지 1층,3_25~50%,3_25~50%,4_50~75%,0.150000,0.150000,...,1.000000,0.000000,0.013807,0.251,0.749,0.504,0.351,0.077,0.052,0.017
67923,202312,경일낙지,20020112,단품요리 전문,제주 제주시 노형동 1291-3번지,5_75~90%,5_75~90%,3_25~50%,0.179310,0.241379,...,0.000000,0.000000,0.825083,0.424,0.576,0.054,0.218,0.379,0.263,0.086
67924,202312,흑돼지가있는풍경,20040109,가정식,제주 제주시 노형동 668번지,2_10~25%,5_75~90%,6_90% 초과,0.066667,0.000000,...,0.733333,0.000000,0.196682,0.574,0.426,0.109,0.188,0.213,0.305,0.185
67925,202312,에이바우트커피삼무공원점,20200602,커피,제주 제주시 연동 260-21번지 1층,6_90% 초과,4_50~75%,1_상위 10% 이하,0.105925,0.125673,...,0.165171,0.000000,0.471193,0.502,0.498,0.306,0.294,0.187,0.154,0.059

In [3]:
def get_concat(path):
    data = pd.DataFrame()
    list = os.listdir(path)
    for i in range(0, len(list)):
        df = pd.read_csv(os.path.join(path, list[i]))
        data = pd.concat([data, df])
    return data

In [4]:
path1 = './data/jt_mt'
path2 = './data/jt_por'
path3 = './data/jt_wk'
path4 = './data/jt_por_info'
jt_mt_df = get_concat(path1)
jt_por_df = get_concat(path2)
jt_wk_df = get_concat(path3)
jt_por_info_df = get_concat(path4)

In [5]:
jt_mt_df

,CL_CD,CL_NM,AREA_NM,ADDR,BASE_YEAR,ALL_TOTAL_CO,JAN_VIEWS_CO,FEB_VIEWS_CO,MAR_VIEWS_CO,APR_VIEWS_CO,MAY_VIEWS_CO,JUN_VIEWS_CO,JULY_VIEWS_CO,AUG_VIEWS_CO,SEP_VIEWS_CO,OCT_VIEWS_CO,NOV_VIEWS_CO,DEC_VIEWS_CO
0,c1,관광지,브랭섬홀아시아 아이스링크,제주특별자치도 서귀포시 대정읍 글로벌에듀로 234(3번게이트),2023,110,110.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,c1,관광지,(주)제주해양레저 투명카약,제주특별자치도 제주시 애월읍 애월로1길 22,2023,68,68.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,c1,관광지,1100고지(휴게소),제주특별자치도 서귀포시 1100로 1555,2023,1587,1587.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,c1,관광지,1100고지습지,제주특별자치도 서귀포시 색달동 산 1-2,2023,4075,4075.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,c1,관광지,1112도로,제주특별자치도 제주시 명림로 584 (봉개동),2023,79,79.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4487,c4,음식점,흑소랑,제주특별자치도 제주시 연북로 631,2023,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0
4488,c4,음식점,흑염소마루,제주특별자치도 서귀포시 남원읍 태위로663번길 1-1,2023,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0
4489,c4,음식점,흑한우명품관,제주특별자치도 서귀포시 일주동로 8421,2023,62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0
4490,c4,음식점,희신이네,제주특별자치도 서귀포시 서홍로 175,2023,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
4491,c4,음식점,힌즈,제주특별자치도 제주시 월대5길 7,2023,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [6]:
jt_por_df

,BASE_YM,CL_NM,TRRSRT_NM,TRRSRT_ADDR,SCORE_VALUE,MOP_CN,REGIST_DE
0,202301.0,공연전시,고흐의 정원,제주 서귀포시 성산읍 삼달신풍로 126-5,0.0,"볼거리,다양",20230130
1,202301.0,공연전시,고흐의 정원,제주 서귀포시 성산읍 삼달신풍로 126-5,0.0,친구,20230130
2,202301.0,공연전시,고흐의 정원,제주 서귀포시 성산읍 삼달신풍로 126-5,0.0,관람객,20230130
3,202301.0,공연전시,고흐의 정원,제주 서귀포시 성산읍 삼달신풍로 126-5,0.0,"파충류,아이,도마뱀,고흐,트릭아트",20230130
4,202301.0,공연전시,고흐의 정원,제주 서귀포시 성산읍 삼달신풍로 126-5,0.0,"사진,아이",20230130
...,...,...,...,...,...,...,...
2584,202312.0,관광호텔,히든 클리프 호텔 앤 네이처,제주특별자치도 서귀포시 상예동 625,7.5,"수영장,여행,가격,도면",20231227
2585,202312.0,관광호텔,히든 클리프 호텔 앤 네이처,제주특별자치도 서귀포시 상예동 625,10.0,새싹,20231228
2586,202312.0,관광호텔,히든 클리프 호텔 앤 네이처,제주특별자치도 서귀포시 상예동 625,5.8,"금고,수영장,직원,깔끔,소음",20231229
2587,202312.0,관광호텔,히든 클리프 호텔 앤 네이처,제주특별자치도 서귀포시 상예동 625,10.0,"수영장,청결,저렴,가격,편의점",20231230
2588,202312.0,관광호텔,히든 클리프 호텔 앤 네이처,제주특별자치도 서귀포시 상예동 625,8.4,"가격,위생,화장실,머리카락,조명",20231231

In [7]:
jt_wk_df

,CL_CD,CL_NM,AREA_NM,ADDR,BASE_YEAR,BASE_MT,ALL_TOTAL_CO,MON_VIEWS_CO,TUES_VIEWS_CO,WED_VIEWS_CO,THUR_VIEWS_CO,FRI_VIEWS_CO,SAT_VIEWS_CO,SUN_VIEWS_CO
0,c1,관광지,브랭섬홀아시아 아이스링크,제주특별자치도 서귀포시 대정읍 글로벌에듀로 234(3번게이트),2023,1,110,15.0,12.0,14.0,16.0,24.0,6.0,23.0
1,c1,관광지,(주)제주해양레저 투명카약,제주특별자치도 제주시 애월읍 애월로1길 22,2023,1,68,11.0,14.0,11.0,5.0,10.0,4.0,13.0
2,c1,관광지,1100고지(휴게소),제주특별자치도 서귀포시 1100로 1555,2023,1,1587,313.0,283.0,222.0,185.0,180.0,154.0,250.0
3,c1,관광지,1100고지습지,제주특별자치도 서귀포시 색달동 산 1-2,2023,1,4075,662.0,643.0,599.0,404.0,541.0,502.0,724.0
4,c1,관광지,1112도로,제주특별자치도 제주시 명림로 584 (봉개동),2023,1,79,17.0,6.0,9.0,11.0,9.0,16.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4487,c4,음식점,흑소랑,제주특별자치도 제주시 연북로 631,2023,12,12,1.0,0.0,2.0,5.0,1.0,3.0,0.0
4488,c4,음식점,흑염소마루,제주특별자치도 서귀포시 남원읍 태위로663번길 1-1,2023,12,28,5.0,0.0,3.0,3.0,8.0,4.0,5.0
4489,c4,음식점,흑한우명품관,제주특별자치도 서귀포시 일주동로 8421,2023,12,62,8.0,7.0,8.0,12.0,9.0,7.0,11.0
4490,c4,음식점,희신이네,제주특별자치도 서귀포시 서홍로 175,2023,12,5,0.0,0.0,0.0,0.0,2.0,2.0,1.0
4491,c4,음식점,힌즈,제주특별자치도 제주시 월대5길 7,2023,12,4,0.0,0.0,1.0,0.0,2.0,0.0,1.0

In [8]:
jt_por_info_df

,CL_NM,TRRSRT_NM,TRRSRT_ADDR,ORIGIN_CL_NM,ANALS_BEGIN_DE,ANALS_END_DE,AVRG_SCORE_VALUE,CORE_KWRD_CN,CORE_KWRD_CO,AFRM_KWRD_CN,AFRM_KWRD_CO,NEGA_KWRD_CN,NEGA_KWRD_CO
0,공연전시,고흐의 정원,제주 서귀포시 성산읍 삼달신풍로 126-5,NAVER,20230101,20230630,0,"파충류,아이,체험,고흐,사진,친절,정원,설명,그림,시간",10,친절,1,NaN,0
1,공연전시,빛의벙커,제주 서귀포시 성산읍 고성리 2039-22,NAVER,20230101,20230630,0,"작품,음악,그림,시간,전시,감상,벙커,관람,제주,아이",10,NaN,0,NaN,0
2,공연전시,세계자동차박물관,제주 서귀포시 안덕면 중산간서로 1610,NAVER,20230101,20230630,0,"자동차,아이,피아노,체험,사슴,먹이,박물관,구경,시간,전시",10,NaN,0,NaN,0
3,공연전시,수목원테마파크,제주 제주시 은수길 69,NAVER,20230101,20230630,0,"아이,체험,썰매,얼음,수목원,테마파크,아이스,시간,사진,어른",10,NaN,0,NaN,0
4,공연전시,아리랑공연장,제주 서귀포시 표선면 번영로 2564-21,NAVER,20230101,20230630,0,"공연,아이,태권도,관람,낙타,사진,만족,부모,한국,시간",10,만족,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,레저관광,제주씨월드(우도잠수함),제주 서귀포시 성산읍 성산등용로 112-7,GOOGLE,20230701,20231231,81,"잠수함,우도,물고기,가격,재미,체험,대비,최고,아이,과정",48,재미,1,NaN,0
253,레저관광,중문승마공원,제주 서귀포시 이어도로 244,GOOGLE,20230701,20231231,88,"아이,친절,호텔,코스,체험,직원,방문,냄새,조련사,생각",38,친절,1,NaN,0
254,자연,천지연폭포,제주 서귀포시 천지동 667-7,GOOGLE,20230701,20231231,87,"폭포,방문,입장료,산책,주차,도보,티켓,이후,주변,제주도",120,NaN,0,NaN,0
255,기타,제주그림카페,제주 서귀포시 안덕면 녹차분재로 218,GOOGLE,20230701,20231231,93,"우주,항공,박물관,아이,카페,가족,추억",7,추억,1,NaN,0
256,기타,난드르깡통구이,제주 서귀포시 안덕면 대평감산로 14,GOOGLE,20230701,20231231,78,"서비스,돼지,맛집,수저,목살,연탄,구이,가격,음식,매장",22,NaN,0,NaN,0